/**
 * 医院信息系统(HIS) 元数据定义
 * 所有代码(SQL/Java/Vue)的唯一数据源，改这里再跑 gen-his.js 即可重新生成
 *
 * 字段属性说明：
 *   name/col/type/sql/cn   基本映射
 *   pk:true                主键
 *   query:'like'|'eq'      列表查询条件
 *   between:true           该字段支持日期范围查询(params.beginXxx/endXxx)
 *   dict:'xxx'             字典类型 -> 表单下拉/单选 + 列表 dict-tag
 *   dictCtl:'radio'        表单用单选(默认下拉)
 *   fk:{api,label,value,module}  外键 -> 表单下拉(远程选项) + 列表显示label
 *   excel:true             @Excel导出注解
 *   persist:false          非持久字段(联查显示用)
 *   list:false             不在表格列显示
 *   form:false             不在表单显示
 *   textarea:true          表单文本域
 *   def:'x'                表单默认值
 *   dateType:'date'|'datetime'
 *   wcol:'x'               查询条件实际列名(联查时覆盖默认 t.col)
 */

const f = (name, col, type, sql, cn, opts = {}) => ({ name, col, type, sql, cn, ...opts });

/** ======================== 字典定义 ======================== */
const DICTS = [
  { type: 'his_dept_type', name: '科室类型', data: [['门诊科室', '0', 'primary'], ['住院病区', '1', 'success'], ['医技科室', '2', 'warning'], ['行政后勤', '3', 'info']] },
  { type: 'his_doctor_title', name: '医生职称', data: [['主任医师', '0', 'danger'], ['副主任医师', '1', 'warning'], ['主治医师', '2', 'primary'], ['住院医师', '3', 'info']] },
  { type: 'his_blood_type', name: '血型', data: [['A型', 'A'], ['B型', 'B'], ['O型', 'O'], ['AB型', 'AB'], ['不详', 'U']] },
  { type: 'his_insurance_type', name: '医保类型', data: [['自费', '0', 'info'], ['医保', '1', 'success'], ['新农合', '2', 'primary'], ['商业保险', '3', 'warning']] },
  { type: 'his_drug_category', name: '药品分类', data: [['抗生素', '0', 'danger'], ['心血管', '1', 'primary'], ['解热镇痛', '2', 'warning'], ['中成药', '3', 'success'], ['注射剂', '4', 'primary'], ['外用药', '5', 'info'], ['其他', '9', 'info']] },
  { type: 'his_rx_type', name: '处方类型', data: [['西药处方', '0', 'primary'], ['中药处方', '1', 'success']] },
  { type: 'his_time_slot', name: '就诊时段', data: [['上午', '0', 'primary'], ['下午', '1', 'warning'], ['晚间', '2', 'info']] },
  { type: 'his_reg_status', name: '挂号状态', data: [['待就诊', '0', 'info'], ['就诊中', '1', 'primary'], ['已诊毕', '2', 'success'], ['已退号', '3', 'danger'], ['已过号', '4', 'warning']] },
  { type: 'his_rx_status', name: '处方状态', data: [['已开立', '0', 'info'], ['已收费', '1', 'primary'], ['已发药', '2', 'success'], ['已作废', '3', 'danger']] },
  { type: 'his_bed_type', name: '床位类型', data: [['普通床位', '0', 'info'], ['重症床位', '1', 'danger'], ['VIP床位', '2', 'warning']] },
  { type: 'his_bed_status', name: '床位状态', data: [['空闲', '0', 'success'], ['占用', '1', 'danger'], ['维修', '2', 'warning'], ['预留', '3', 'info']] },
  { type: 'his_adm_status', name: '住院状态', data: [['在院', '0', 'primary'], ['已出院', '1', 'success']] },
  { type: 'his_order_type', name: '医嘱类型', data: [['长期医嘱', '0', 'primary'], ['临时医嘱', '1', 'warning']] },
  { type: 'his_order_status', name: '医嘱状态', data: [['已开立', '0', 'info'], ['已执行', '1', 'success'], ['已停止', '2', 'danger']] },
  { type: 'his_charge_type', name: '费用类型', data: [['挂号费', '0', 'primary'], ['处方费', '1', 'success'], ['检验费', '2', 'warning'], ['检查费', '3', 'warning'], ['住院费', '4', 'danger'], ['手术费', '5', 'danger'], ['其他', '9', 'info']] },
  { type: 'his_charge_status', name: '收费状态', data: [['未收费', '0', 'danger'], ['已收费', '1', 'success'], ['已退费', '2', 'info']] },
  { type: 'his_pay_type', name: '支付方式', data: [['现金', '0', 'success'], ['扫码支付', '1', 'primary'], ['医保', '2', 'warning'], ['银行卡', '3', 'info']] },
  { type: 'his_lab_status', name: '检验状态', data: [['已申请', '0', 'info'], ['已采样', '1', 'primary'], ['检验中', '2', 'warning'], ['已出报告', '3', 'success'], ['已作废', '4', 'danger']] },
  { type: 'his_sample_type', name: '标本类型', data: [['血液', '0', 'danger'], ['尿液', '1', 'warning'], ['粪便', '2', 'info'], ['分泌物', '3', 'info'], ['其他', '9', 'info']] },
  { type: 'his_lab_flag', name: '检验结果标识', data: [['正常', '0', 'success'], ['偏高', '1', 'danger'], ['偏低', '2', 'primary']] },
  { type: 'his_exam_type', name: '检查类型', data: [['CT', '0', 'primary'], ['MRI核磁', '1', 'warning'], ['X光', '2', 'info'], ['B超', '3', 'success'], ['心电图', '4', 'danger'], ['内镜', '5', 'warning']] },
  { type: 'his_exam_status', name: '检查状态', data: [['已申请', '0', 'info'], ['已检查', '1', 'primary'], ['已出报告', '2', 'success'], ['已取消', '3', 'danger']] },
  { type: 'his_surgery_level', name: '手术级别', data: [['一级手术', '0', 'info'], ['二级手术', '1', 'primary'], ['三级手术', '2', 'warning'], ['四级手术', '3', 'danger']] },
  { type: 'his_surgery_status', name: '手术状态', data: [['已预约', '0', 'info'], ['手术中', '1', 'warning'], ['已完成', '2', 'success'], ['已取消', '3', 'danger']] },
  { type: 'his_anesthesia', name: '麻醉方式', data: [['全身麻醉', '0', 'danger'], ['局部麻醉', '1', 'success'], ['腰椎麻醉', '2', 'warning'], ['硬膜外麻醉', '3', 'primary']] },
  { type: 'his_stock_type', name: '库存变动类型', data: [['采购入库', '0', 'success'], ['发药出库', '1', 'danger'], ['退药入库', '2', 'warning'], ['盘盈', '3', 'success'], ['盘亏', '4', 'danger']] },
  { type: 'his_purchase_status', name: '采购单状态', data: [['待审核', '0', 'warning'], ['已入库', '1', 'success'], ['已取消', '2', 'info']] },
  { type: 'his_fee_category', name: '收费项目类别', data: [['检验费', '0', 'warning'], ['检查费', '1', 'primary'], ['手术费', '2', 'danger'], ['床位费', '3', 'success'], ['护理费', '4', 'info'], ['诊疗费', '5', 'primary'], ['其他', '9', 'info']] },
  { type: 'his_schedule_status', name: '排班状态', data: [['开放挂号', '0', 'success'], ['停诊', '1', 'danger'], ['约满', '2', 'warning']] },
  { type: 'his_visit_status', name: '就诊状态', data: [['接诊中', '0', 'primary'], ['已完诊', '1', 'success']] },
];

/** ======================== 实体定义 ======================== */
const ENTITIES = [
  // ================= 基础数据 =================
  {
    table: 'his_department', entity: 'Department', cn: '科室', path: 'dept', group: 'base', pk: 'deptId', pkCol: 'dept_id',
    fields: [
      f('deptId', 'dept_id', 'Long', 'bigint(20)', '科室ID', { pk: true }),
      f('parentId', 'parent_id', 'Long', 'bigint(20)', '上级科室', { def: 0, list: false }),
      f('deptName', 'dept_name', 'String', 'varchar(50)', '科室名称', { query: 'like', required: true, excel: true }),
      f('deptCode', 'dept_code', 'String', 'varchar(30)', '科室编码', { required: true, excel: true }),
      f('deptType', 'dept_type', 'String', 'char(1)', '科室类型', { dict: 'his_dept_type', required: true, excel: true, def: '0' }),
      f('location', 'location', 'String', 'varchar(100)', '位置'),
      f('phone', 'phone', 'String', 'varchar(20)', '联系电话'),
      f('intro', 'intro', 'String', 'varchar(500)', '科室简介', { textarea: true, list: false }),
      f('orderNum', 'order_num', 'Integer', 'int(4)', '排序', { def: 0 }),
      f('status', 'status', 'String', "char(1)", '状态', { dict: 'sys_normal_disable', dictCtl: 'radio', def: '0' }),
    ],
    orderBy: 't.order_num, t.dept_id',
  },
  {
    table: 'his_doctor', entity: 'Doctor', cn: '医生', path: 'doctor', group: 'base', pk: 'doctorId', pkCol: 'doctor_id',
    fields: [
      f('doctorId', 'doctor_id', 'Long', 'bigint(20)', '医生ID', { pk: true }),
      f('doctorName', 'doctor_name', 'String', 'varchar(50)', '医生姓名', { query: 'like', required: true, excel: true }),
      f('deptId', 'dept_id', 'Long', 'bigint(20)', '所属科室', { required: true, query: 'eq', fk: { api: 'listDepartment', module: 'dept', label: 'deptName', value: 'deptId' } }),
      f('deptName', '', 'String', '', '所属科室', { persist: false, form: false, joinCol: 'd.dept_name' }),
      f('title', 'title', 'String', 'char(1)', '职称', { dict: 'his_doctor_title', required: true, excel: true, def: '2' }),
      f('gender', 'gender', 'String', 'char(1)', '性别', { dict: 'sys_user_sex', def: '0' }),
      f('phone', 'phone', 'String', 'varchar(20)', '联系电话'),
      f('specialty', 'specialty', 'String', 'varchar(200)', '擅长领域'),
      f('regFee', 'reg_fee', 'BigDecimal', 'decimal(10,2)', '挂号费(元)', { required: true, def: 10 }),
      f('intro', 'intro', 'String', 'varchar(500)', '个人简介', { textarea: true, list: false }),
      f('status', 'status', 'String', "char(1)", '状态', { dict: 'sys_normal_disable', dictCtl: 'radio', def: '0' }),
    ],
    joins: [{ alias: 'd', table: 'his_department', on: 'd.dept_id = t.dept_id' }],
    orderBy: 't.doctor_id',
  },
  {
    table: 'his_patient', entity: 'Patient', cn: '患者', path: 'patient', group: 'base', pk: 'patientId', pkCol: 'patient_id', complex: true,
    fields: [
      f('patientId', 'patient_id', 'Long', 'bigint(20)', '患者ID', { pk: true }),
      f('patientNo', 'patient_no', 'String', 'varchar(20)', '就诊卡号', { query: 'eq', required: true, excel: true }),
      f('patientName', 'patient_name', 'String', 'varchar(50)', '患者姓名', { query: 'like', required: true, excel: true }),
      f('gender', 'gender', 'String', 'char(1)', '性别', { dict: 'sys_user_sex', dictCtl: 'radio', required: true, def: '0' }),
      f('birthDate', 'birth_date', 'Date', 'date', '出生日期', { dateType: 'date' }),
      f('age', 'age', 'Integer', 'int(4)', '年龄'),
      f('idCard', 'id_card', 'String', 'varchar(18)', '身份证号', { query: 'eq' }),
      f('phone', 'phone', 'String', 'varchar(20)', '联系电话', { query: 'eq', required: true }),
      f('address', 'address', 'String', 'varchar(200)', '住址', { list: false }),
      f('bloodType', 'blood_type', 'String', 'char(2)', '血型', { dict: 'his_blood_type' }),
      f('insuranceType', 'insurance_type', 'String', 'char(1)', '医保类型', { dict: 'his_insurance_type', def: '0' }),
      f('allergy', 'allergy', 'String', 'varchar(200)', '过敏史', { list: false }),
      f('status', 'status', 'String', "char(1)", '状态', { dict: 'sys_normal_disable', dictCtl: 'radio', def: '0' }),
    ],
    orderBy: 't.patient_id desc',
  },
  {
    table: 'his_drug', entity: 'Drug', cn: '药品', path: 'drug', group: 'base', pk: 'drugId', pkCol: 'drug_id',
    fields: [
      f('drugId', 'drug_id', 'Long', 'bigint(20)', '药品ID', { pk: true }),
      f('drugCode', 'drug_code', 'String', 'varchar(30)', '药品编码', { required: true, query: 'eq' }),
      f('drugName', 'drug_name', 'String', 'varchar(100)', '药品名称', { query: 'like', required: true, excel: true }),
      f('category', 'category', 'String', 'char(1)', '药品分类', { dict: 'his_drug_category', required: true, excel: true, def: '9' }),
      f('specification', 'specification', 'String', 'varchar(50)', '规格', { required: true }),
      f('unit', 'unit', 'String', 'varchar(10)', '单位', { required: true, def: '盒' }),
      f('price', 'price', 'BigDecimal', 'decimal(10,2)', '单价(元)', { required: true, excel: true }),
      f('stock', 'stock', 'Integer', 'int(11)', '库存', { required: true, def: 0 }),
      f('stockWarn', 'stock_warn', 'Integer', 'int(11)', '预警库存', { def: 50 }),
      f('manufacturer', 'manufacturer', 'String', 'varchar(100)', '生产厂家', { list: false }),
      f('approvalNo', 'approval_no', 'String', 'varchar(50)', '批准文号', { list: false }),
      f('isPrescription', 'is_prescription', 'String', 'char(1)', '处方药', { dict: 'sys_yes_no', dictCtl: 'radio', def: 'N' }),
      f('status', 'status', 'String', "char(1)", '状态', { dict: 'sys_normal_disable', dictCtl: 'radio', def: '0' }),
    ],
    orderBy: 't.drug_id',
  },
  {
    table: 'his_supplier', entity: 'Supplier', cn: '供应商', path: 'supplier', group: 'base', pk: 'supplierId', pkCol: 'supplier_id',
    fields: [
      f('supplierId', 'supplier_id', 'Long', 'bigint(20)', '供应商ID', { pk: true }),
      f('supplierName', 'supplier_name', 'String', 'varchar(100)', '供应商名称', { query: 'like', required: true, excel: true }),
      f('contact', 'contact', 'String', 'varchar(50)', '联系人'),
      f('phone', 'phone', 'String', 'varchar(20)', '联系电话'),
      f('address', 'address', 'String', 'varchar(200)', '地址'),
      f('status', 'status', 'String', "char(1)", '状态', { dict: 'sys_normal_disable', dictCtl: 'radio', def: '0' }),
    ],
    orderBy: 't.supplier_id',
  },
  {
    table: 'his_fee_item', entity: 'FeeItem', cn: '收费项目', path: 'feeitem', group: 'base', pk: 'itemId', pkCol: 'item_id',
    fields: [
      f('itemId', 'item_id', 'Long', 'bigint(20)', '项目ID', { pk: true }),
      f('itemName', 'item_name', 'String', 'varchar(100)', '项目名称', { query: 'like', required: true, excel: true }),
      f('category', 'category', 'String', 'char(1)', '项目类别', { dict: 'his_fee_category', required: true, excel: true, def: '9' }),
      f('price', 'price', 'BigDecimal', 'decimal(10,2)', '单价(元)', { required: true, excel: true }),
      f('unit', 'unit', 'String', 'varchar(10)', '单位', { def: '次' }),
      f('status', 'status', 'String', "char(1)", '状态', { dict: 'sys_normal_disable', dictCtl: 'radio', def: '0' }),
    ],
    orderBy: 't.item_id',
  },
  {
    table: 'his_ward', entity: 'Ward', cn: '病区', path: 'ward', group: 'base', pk: 'wardId', pkCol: 'ward_id',
    fields: [
      f('wardId', 'ward_id', 'Long', 'bigint(20)', '病区ID', { pk: true }),
      f('wardName', 'ward_name', 'String', 'varchar(50)', '病区名称', { query: 'like', required: true, excel: true }),
      f('deptId', 'dept_id', 'Long', 'bigint(20)', '所属科室', { required: true, fk: { api: 'listDepartment', module: 'dept', label: 'deptName', value: 'deptId' } }),
      f('deptName', '', 'String', '', '所属科室', { persist: false, form: false, joinCol: 'd.dept_name' }),
      f('location', 'location', 'String', 'varchar(100)', '位置'),
      f('nurseCount', 'nurse_count', 'Integer', 'int(4)', '护士人数', { def: 5 }),
      f('status', 'status', 'String', "char(1)", '状态', { dict: 'sys_normal_disable', dictCtl: 'radio', def: '0' }),
    ],
    joins: [{ alias: 'd', table: 'his_department', on: 'd.dept_id = t.dept_id' }],
    orderBy: 't.ward_id',
  },
  {
    table: 'his_bed', entity: 'Bed', cn: '床位', path: 'bed', group: 'base', pk: 'bedId', pkCol: 'bed_id', complex: true,
    fields: [
      f('bedId', 'bed_id', 'Long', 'bigint(20)', '床位ID', { pk: true }),
      f('wardId', 'ward_id', 'Long', 'bigint(20)', '所属病区', { required: true, query: 'eq', fk: { api: 'listWard', module: 'ward', label: 'wardName', value: 'wardId' } }),
      f('wardName', '', 'String', '', '所属病区', { persist: false, form: false, joinCol: 'w.ward_name' }),
      f('bedNo', 'bed_no', 'String', 'varchar(20)', '床号', { required: true }),
      f('bedType', 'bed_type', 'String', 'char(1)', '床位类型', { dict: 'his_bed_type', def: '0' }),
      f('pricePerDay', 'price_per_day', 'BigDecimal', 'decimal(10,2)', '每日价格(元)', { def: 60 }),
      f('status', 'status', 'String', "char(1)", '床位状态', { dict: 'his_bed_status', def: '0' }),
      // 联查:当前在住患者
      f('patientName', '', 'String', '', '在住患者', { persist: false, form: false, joinCol: '(select p.patient_name from his_admission a join his_patient p on p.patient_id=a.patient_id where a.bed_id=t.bed_id and a.adm_status=\'0\' limit 1)' }),
    ],
    joins: [{ alias: 'w', table: 'his_ward', on: 'w.ward_id = t.ward_id' }],
    orderBy: 't.ward_id, t.bed_no',
    extraMapper: `    /** 查询病区下空闲床位 */\n    public List<Bed> selectFreeBeds(Long wardId);`,
    extraService: `    /** 查询病区下空闲床位 */\n    public List<Bed> selectFreeBeds(Long wardId);`,
    extraImpl: `    @Override\n    public List<Bed> selectFreeBeds(Long wardId) { return bedMapper.selectFreeBeds(wardId); }`,
    extraXml: `    <select id="selectFreeBeds" parameterType="Long" resultMap="BedResult">\n        select t.* from his_bed t where t.ward_id = #{wardId} and t.status = '0' order by t.bed_no\n    </select>`,
    extraApi: `// 查询病区空闲床位\nexport function listFreeBed(wardId) {\n  return request({ url: '/his/bed/free/' + wardId, method: 'get' })\n}\n\n// 修改床位状态\nexport function changeBedStatus(bedId, status) {\n  return request({ url: '/his/bed/status/' + bedId + '/' + status, method: 'put' })\n}`,
    extraController: `    /** 查询病区空闲床位 */\n    @GetMapping("/free/{wardId}")\n    public AjaxResult freeBeds(@PathVariable("wardId") Long wardId)\n    {\n        return success(bedService.selectFreeBeds(wardId));\n    }\n\n    /** 修改床位状态 */\n    @PreAuthorize("@ss.hasPermi('his:bed:edit')")\n    @Log(title = "床位", businessType = BusinessType.UPDATE)\n    @PutMapping("/status/{bedId}/{status}")\n    public AjaxResult changeStatus(@PathVariable("bedId") Long bedId, @PathVariable("status") String status)\n    {\n        Bed bed = new Bed();\n        bed.setBedId(bedId);\n        bed.setStatus(status);\n        return toAjax(bedService.updateBed(bed));\n    }`,
  },
  // ================= 门诊 =================
  {
    table: 'his_schedule', entity: 'Schedule', cn: '排班', path: 'schedule', group: 'outpatient', pk: 'scheduleId', pkCol: 'schedule_id',
    fields: [
      f('scheduleId', 'schedule_id', 'Long', 'bigint(20)', '排班ID', { pk: true }),
      f('deptId', 'dept_id', 'Long', 'bigint(20)', '科室', { required: true, query: 'eq', fk: { api: 'listDepartment', module: 'dept', label: 'deptName', value: 'deptId' } }),
      f('deptName', '', 'String', '', '科室', { persist: false, form: false, joinCol: 'd.dept_name' }),
      f('doctorId', 'doctor_id', 'Long', 'bigint(20)', '医生', { required: true, query: 'eq', fk: { api: 'listDoctor', module: 'doctor', label: 'doctorName', value: 'doctorId' } }),
      f('doctorName', '', 'String', '', '医生', { persist: false, form: false, joinCol: 'doc.doctor_name' }),
      f('doctorTitle', '', 'String', '', '职称', { persist: false, form: false, joinCol: 'doc.title', dict: 'his_doctor_title' }),
      f('workDate', 'work_date', 'Date', 'date', '出诊日期', { required: true, query: 'eq', dateType: 'date', excel: true }),
      f('timeSlot', 'time_slot', 'String', 'char(1)', '时段', { dict: 'his_time_slot', dictCtl: 'radio', required: true, def: '0', excel: true }),
      f('quota', 'quota', 'Integer', 'int(4)', '总号源', { required: true, def: 20 }),
      f('remainQuota', 'remain_quota', 'Integer', 'int(4)', '剩余号源', { required: true, def: 20 }),
      f('status', 'status', 'String', "char(1)", '状态', { dict: 'his_schedule_status', def: '0' }),
    ],
    joins: [
      { alias: 'd', table: 'his_department', on: 'd.dept_id = t.dept_id' },
      { alias: 'doc', table: 'his_doctor', on: 'doc.doctor_id = t.doctor_id' },
    ],
    orderBy: 't.work_date desc, t.time_slot',
    extraMapper: `    /** 扣减号源(剩余号源-1，剩号>0才成功) */\n    public int decrQuota(Long scheduleId);\n\n    /** 恢复号源 */\n    public int incrQuota(Long scheduleId);\n\n    /** 查询可挂号排班(剩余>0) */\n    public List<Schedule> selectAvailable(Schedule schedule);`,
    extraService: `    /** 查询可挂号排班 */\n    public List<Schedule> selectAvailable(Schedule schedule);`,
    extraImpl: `    @Override\n    public List<Schedule> selectAvailable(Schedule schedule) { return scheduleMapper.selectAvailable(schedule); }`,
    extraXml: `    <update id="decrQuota" parameterType="Long">\n        update his_schedule set remain_quota = remain_quota - 1\n        where schedule_id = #{scheduleId} and remain_quota &gt; 0\n    </update>\n\n    <update id="incrQuota" parameterType="Long">\n        update his_schedule set remain_quota = least(quota, remain_quota + 1)\n        where schedule_id = #{scheduleId}\n    </update>\n\n    <select id="selectAvailable" parameterType="com.ruoyi.his.domain.Schedule" resultMap="ScheduleResult">\n        <include refid="selectScheduleVo"/>\n        <where>\n            t.remain_quota &gt; 0 and t.status = '0'\n            <if test="deptId != null"> AND t.dept_id = #{deptId}</if>\n            <if test="doctorId != null"> AND t.doctor_id = #{doctorId}</if>\n            <if test="workDate != null"> AND t.work_date = #{workDate}</if>\n        </where>\n        order by t.work_date, t.time_slot\n    </select>`,
    extraApi: `// 查询可挂号排班\nexport function listAvailableSchedule(query) {\n  return request({ url: '/his/schedule/available', method: 'get', params: query })\n}`,
    extraController: `    /** 查询可挂号排班(挂号页联动用) */\n    @GetMapping("/available")\n    public TableDataInfo available(Schedule schedule)\n    {\n        List<Schedule> list = scheduleService.selectAvailable(schedule);\n        return getDataTable(list);\n    }`,
  },
  {
    table: 'his_registration', entity: 'Registration', cn: '挂号', path: 'registration', group: 'outpatient', pk: 'regId', pkCol: 'reg_id', complex: true,
    fields: [
      f('regId', 'reg_id', 'Long', 'bigint(20)', '挂号ID', { pk: true }),
      f('regNo', 'reg_no', 'String', 'varchar(30)', '挂号单号', { query: 'eq' }),
      f('patientId', 'patient_id', 'Long', 'bigint(20)', '患者', { required: true, query: 'eq' }),
      f('patientName', '', 'String', '', '患者姓名', { persist: false, form: false, joinCol: 'p.patient_name' }),
      f('patientNo', '', 'String', '', '就诊卡号', { persist: false, form: false, joinCol: 'p.patient_no' }),
      f('gender', '', 'String', '', '性别', { persist: false, form: false, joinCol: 'p.gender', dict: 'sys_user_sex' }),
      f('age', '', 'Integer', '', '年龄', { persist: false, form: false, joinCol: 'p.age' }),
      f('deptId', 'dept_id', 'Long', 'bigint(20)', '科室', { required: true, query: 'eq' }),
      f('deptName', '', 'String', '', '科室', { persist: false, form: false, joinCol: 'd.dept_name' }),
      f('doctorId', 'doctor_id', 'Long', 'bigint(20)', '医生', { required: true, query: 'eq' }),
      f('doctorName', '', 'String', '', '医生', { persist: false, form: false, joinCol: 'doc.doctor_name' }),
      f('scheduleId', 'schedule_id', 'Long', 'bigint(20)', '排班ID'),
      f('regDate', 'reg_date', 'Date', 'date', '就诊日期', { dateType: 'date', query: 'eq' }),
      f('timeSlot', 'time_slot', 'String', 'char(1)', '时段', { dict: 'his_time_slot' }),
      f('queueNo', 'queue_no', 'Integer', 'int(4)', '排队号'),
      f('regFee', 'reg_fee', 'BigDecimal', 'decimal(10,2)', '挂号费(元)'),
      f('visitStatus', 'visit_status', 'String', 'char(1)', '状态', { dict: 'his_reg_status', def: '0', query: 'eq' }),
      f('payStatus', 'pay_status', 'String', 'char(1)', '缴费状态', { dict: 'his_charge_status', def: '0' }),
    ],
    joins: [
      { alias: 'p', table: 'his_patient', on: 'p.patient_id = t.patient_id' },
      { alias: 'd', table: 'his_department', on: 'd.dept_id = t.dept_id' },
      { alias: 'doc', table: 'his_doctor', on: 'doc.doctor_id = t.doctor_id' },
    ],
    orderBy: 't.reg_id desc',
    hasExtraCode: 'registration',
  },
  {
    table: 'his_visit', entity: 'Visit', cn: '就诊记录', path: 'visit', group: 'outpatient', pk: 'visitId', pkCol: 'visit_id', view: 'emr',
    fields: [
      f('visitId', 'visit_id', 'Long', 'bigint(20)', '就诊ID', { pk: true }),
      f('visitNo', 'visit_no', 'String', 'varchar(30)', '就诊编号', { query: 'eq' }),
      f('regId', 'reg_id', 'Long', 'bigint(20)', '挂号ID', { query: 'eq' }),
      f('patientId', 'patient_id', 'Long', 'bigint(20)', '患者', { query: 'eq' }),
      f('patientName', '', 'String', '', '患者姓名', { persist: false, form: false, joinCol: 'p.patient_name' }),
      f('doctorId', 'doctor_id', 'Long', 'bigint(20)', '医生', { query: 'eq' }),
      f('doctorName', '', 'String', '', '医生', { persist: false, form: false, joinCol: 'doc.doctor_name' }),
      f('deptId', 'dept_id', 'Long', 'bigint(20)', '科室'),
      f('deptName', '', 'String', '', '科室', { persist: false, form: false, joinCol: 'd.dept_name' }),
      f('visitTime', 'visit_time', 'Date', 'datetime', '就诊时间', { dateType: 'datetime' }),
      f('chiefComplaint', 'chief_complaint', 'String', 'varchar(500)', '主诉', { textarea: true, list: false }),
      f('presentIllness', 'present_illness', 'String', 'varchar(1000)', '现病史', { textarea: true, list: false }),
      f('pastIllness', 'past_illness', 'String', 'varchar(500)', '既往史', { textarea: true, list: false }),
      f('diagnosis', 'diagnosis', 'String', 'varchar(500)', '诊断结果', { textarea: true }),
      f('treatment', 'treatment', 'String', 'varchar(500)', '处理意见', { textarea: true, list: false }),
      f('status', 'status', 'String', "char(1)", '就诊状态', { dict: 'his_visit_status', def: '0' }),
    ],
    joins: [
      { alias: 'p', table: 'his_patient', on: 'p.patient_id = t.patient_id' },
      { alias: 'd', table: 'his_department', on: 'd.dept_id = t.dept_id' },
      { alias: 'doc', table: 'his_doctor', on: 'doc.doctor_id = t.doctor_id' },
    ],
    orderBy: 't.visit_id desc',
    extraApi: `// 完成就诊\nexport function finishVisit(visitId) {\n  return request({ url: '/his/visit/finish/' + visitId, method: 'put' })\n}`,
    extraController: `    /** 完成就诊(病历完诊 -> 挂号状态置为已诊毕) */\n    @PreAuthorize("@ss.hasPermi('his:visit:edit')")\n    @Log(title = "就诊记录", businessType = BusinessType.UPDATE)\n    @PutMapping("/finish/{visitId}")\n    public AjaxResult finish(@PathVariable("visitId") Long visitId)\n    {\n        return toAjax(visitService.finishVisit(visitId));\n    }`,
    extraService: `    /** 完成就诊 */\n    public int finishVisit(Long visitId);`,
    extraImpl: `    /** 完成就诊：病历状态置完诊，同时更新挂号单为已诊毕 */\n    @Override\n    @Transactional\n    public int finishVisit(Long visitId)\n    {\n        Visit visit = visitMapper.selectVisitByVisitId(visitId);\n        if (visit == null) { return 0; }\n        Visit upd = new Visit();\n        upd.setVisitId(visitId);\n        upd.setStatus("1");\n        int rows = visitMapper.updateVisit(upd);\n        if (visit.getRegId() != null)\n        {\n            registrationMapper.updateVisitStatus(visit.getRegId(), "2");\n        }\n        return rows;\n    }`,
    extraImplImports: ['com.ruoyi.his.mapper.RegistrationMapper', 'org.springframework.transaction.annotation.Transactional'],
    extraImplAutowired: ['RegistrationMapper registrationMapper'],
  },
  {
    table: 'his_prescription', entity: 'Prescription', cn: '处方', path: 'prescription', group: 'outpatient', pk: 'rxId', pkCol: 'rx_id', complex: true, master: 'PrescriptionItem',
    fields: [
      f('rxId', 'rx_id', 'Long', 'bigint(20)', '处方ID', { pk: true }),
      f('rxNo', 'rx_no', 'String', 'varchar(30)', '处方号', { query: 'eq' }),
      f('visitId', 'visit_id', 'Long', 'bigint(20)', '就诊ID'),
      f('patientId', 'patient_id', 'Long', 'bigint(20)', '患者', { query: 'eq' }),
      f('patientName', '', 'String', '', '患者姓名', { persist: false, form: false, joinCol: 'p.patient_name' }),
      f('doctorId', 'doctor_id', 'Long', 'bigint(20)', '医生'),
      f('doctorName', '', 'String', '', '医生', { persist: false, form: false, joinCol: 'doc.doctor_name' }),
      f('rxType', 'rx_type', 'String', 'char(1)', '处方类型', { dict: 'his_rx_type', def: '0' }),
      f('totalAmount', 'total_amount', 'BigDecimal', 'decimal(10,2)', '合计金额(元)'),
      f('status', 'status', 'String', 'char(1)', '状态', { dict: 'his_rx_status', def: '0', query: 'eq' }),
      f('dispenseBy', 'dispense_by', 'String', 'varchar(64)', '发药药师', { list: false }),
      f('dispenseTime', 'dispense_time', 'Date', 'datetime', '发药时间', { dateType: 'datetime', list: false }),
    ],
    joins: [
      { alias: 'p', table: 'his_patient', on: 'p.patient_id = t.patient_id' },
      { alias: 'doc', table: 'his_doctor', on: 'doc.doctor_id = t.doctor_id' },
    ],
    orderBy: 't.rx_id desc',
    hasExtraCode: 'prescription',
  },
  {
    table: 'his_prescription_item', entity: 'PrescriptionItem', cn: '处方明细', path: 'prescriptionItem', group: 'outpatient', pk: 'itemId', pkCol: 'item_id', noPage: true,
    fields: [
      f('itemId', 'item_id', 'Long', 'bigint(20)', '明细ID', { pk: true }),
      f('rxId', 'rx_id', 'Long', 'bigint(20)', '处方ID', { query: 'eq' }),
      f('drugId', 'drug_id', 'Long', 'bigint(20)', '药品'),
      f('drugName', 'drug_name', 'String', 'varchar(100)', '药品名称'),
      f('specification', 'specification', 'String', 'varchar(50)', '规格'),
      f('unit', 'unit', 'String', 'varchar(10)', '单位'),
      f('price', 'price', 'BigDecimal', 'decimal(10,2)', '单价(元)'),
      f('quantity', 'quantity', 'Integer', 'int(11)', '数量'),
      f('amount', 'amount', 'BigDecimal', 'decimal(10,2)', '金额(元)'),
      f('usageDose', 'usage_dose', 'String', 'varchar(100)', '用法用量'),
      f('frequency', 'frequency', 'String', 'varchar(50)', '频次'),
      f('days', 'days', 'Integer', 'int(4)', '天数'),
    ],
    orderBy: 't.item_id',
    noController: true,
  },
  {
    table: 'his_charge', entity: 'Charge', cn: '费用单', path: 'charge', group: 'outpatient', pk: 'chargeId', pkCol: 'charge_id', complex: true, createTimeQuery: true,
    fields: [
      f('chargeId', 'charge_id', 'Long', 'bigint(20)', '费用ID', { pk: true }),
      f('chargeNo', 'charge_no', 'String', 'varchar(30)', '单据号', { query: 'eq' }),
      f('patientId', 'patient_id', 'Long', 'bigint(20)', '患者', { query: 'eq' }),
      f('patientName', '', 'String', '', '患者姓名', { persist: false, form: false, joinCol: 'p.patient_name' }),
      f('patientNo', '', 'String', '', '就诊卡号', { persist: false, form: false, joinCol: 'p.patient_no' }),
      f('sourceType', 'source_type', 'String', 'char(1)', '费用类型', { dict: 'his_charge_type', query: 'eq' }),
      f('sourceId', 'source_id', 'Long', 'bigint(20)', '来源单据ID'),
      f('itemName', 'item_name', 'String', 'varchar(100)', '项目名称', { query: 'like' }),
      f('price', 'price', 'BigDecimal', 'decimal(10,2)', '单价(元)'),
      f('quantity', 'quantity', 'Integer', 'int(11)', '数量', { def: 1 }),
      f('amount', 'amount', 'BigDecimal', 'decimal(10,2)', '金额(元)'),
      f('chargeStatus', 'charge_status', 'String', 'char(1)', '收费状态', { dict: 'his_charge_status', def: '0', query: 'eq' }),
      f('payType', 'pay_type', 'String', 'char(1)', '支付方式', { dict: 'his_pay_type' }),
      f('settleTime', 'settle_time', 'Date', 'datetime', '结算时间', { dateType: 'datetime', list: false }),
      f('operator', 'operator', 'String', 'varchar(64)', '收费员', { list: false }),
    ],
    joins: [{ alias: 'p', table: 'his_patient', on: 'p.patient_id = t.patient_id' }],
    orderBy: 't.charge_id desc',
    hasExtraCode: 'charge',
  },
  // ================= 住院 =================
  {
    table: 'his_admission', entity: 'Admission', cn: '住院登记', path: 'admission', group: 'inpatient', pk: 'admId', pkCol: 'adm_id', complex: true,
    fields: [
      f('admId', 'adm_id', 'Long', 'bigint(20)', '住院ID', { pk: true }),
      f('admNo', 'adm_no', 'String', 'varchar(30)', '住院号', { query: 'eq' }),
      f('patientId', 'patient_id', 'Long', 'bigint(20)', '患者', { query: 'eq' }),
      f('patientName', '', 'String', '', '患者姓名', { persist: false, form: false, joinCol: 'p.patient_name' }),
      f('gender', '', 'String', '', '性别', { persist: false, form: false, joinCol: 'p.gender', dict: 'sys_user_sex' }),
      f('age', '', 'Integer', '', '年龄', { persist: false, form: false, joinCol: 'p.age' }),
      f('deptId', 'dept_id', 'Long', 'bigint(20)', '科室', { query: 'eq' }),
      f('deptName', '', 'String', '', '科室', { persist: false, form: false, joinCol: 'd.dept_name' }),
      f('wardId', 'ward_id', 'Long', 'bigint(20)', '病区'),
      f('wardName', '', 'String', '', '病区', { persist: false, form: false, joinCol: 'w.ward_name' }),
      f('bedId', 'bed_id', 'Long', 'bigint(20)', '床位'),
      f('bedNo', '', 'String', '', '床号', { persist: false, form: false, joinCol: 'b.bed_no' }),
      f('doctorId', 'doctor_id', 'Long', 'bigint(20)', '主治医生'),
      f('doctorName', '', 'String', '', '主治医生', { persist: false, form: false, joinCol: 'doc.doctor_name' }),
      f('inDate', 'in_date', 'Date', 'datetime', '入院时间', { dateType: 'datetime' }),
      f('outDate', 'out_date', 'Date', 'datetime', '出院时间', { dateType: 'datetime', list: false }),
      f('deposit', 'deposit', 'BigDecimal', 'decimal(10,2)', '预缴押金(元)', { def: 1000 }),
      f('admStatus', 'adm_status', 'String', 'char(1)', '住院状态', { dict: 'his_adm_status', def: '0', query: 'eq' }),
      f('diagnosisIn', 'diagnosis_in', 'String', 'varchar(500)', '入院诊断', { textarea: true, list: false }),
    ],
    joins: [
      { alias: 'p', table: 'his_patient', on: 'p.patient_id = t.patient_id' },
      { alias: 'd', table: 'his_department', on: 'd.dept_id = t.dept_id' },
      { alias: 'w', table: 'his_ward', on: 'w.ward_id = t.ward_id' },
      { alias: 'b', table: 'his_bed', on: 'b.bed_id = t.bed_id' },
      { alias: 'doc', table: 'his_doctor', on: 'doc.doctor_id = t.doctor_id' },
    ],
    orderBy: 't.adm_id desc',
    hasExtraCode: 'admission',
  },
  {
    table: 'his_medical_order', entity: 'MedicalOrder', cn: '医嘱', path: 'order', group: 'inpatient', pk: 'orderId', pkCol: 'order_id', complex: true,
    fields: [
      f('orderId', 'order_id', 'Long', 'bigint(20)', '医嘱ID', { pk: true }),
      f('admId', 'adm_id', 'Long', 'bigint(20)', '住院ID', { query: 'eq' }),
      f('admNo', '', 'String', '', '住院号', { persist: false, form: false, joinCol: 'a.adm_no' }),
      f('patientId', 'patient_id', 'Long', 'bigint(20)', '患者', { query: 'eq' }),
      f('patientName', '', 'String', '', '患者姓名', { persist: false, form: false, joinCol: 'p.patient_name' }),
      f('doctorId', 'doctor_id', 'Long', 'bigint(20)', '开立医生', { fk: { api: 'listDoctor', module: 'doctor', label: 'doctorName', value: 'doctorId' } }),
      f('doctorName', '', 'String', '', '开立医生', { persist: false, form: false, joinCol: 'doc.doctor_name' }),
      f('orderType', 'order_type', 'String', 'char(1)', '医嘱类型', { dict: 'his_order_type', dictCtl: 'radio', required: true, def: '1' }),
      f('content', 'content', 'String', 'varchar(500)', '医嘱内容', { textarea: true, required: true }),
      f('drugId', 'drug_id', 'Long', 'bigint(20)', '关联药品', { fk: { api: 'listDrug', module: 'drug', label: 'drugName', value: 'drugId' }, list: false }),
      f('drugName', '', 'String', '', '关联药品', { persist: false, form: false, joinCol: 'dg.drug_name' }),
      f('dose', 'dose', 'String', 'varchar(50)', '单次剂量'),
      f('frequency', 'frequency', 'String', 'varchar(50)', '频次'),
      f('startTime', 'start_time', 'Date', 'datetime', '开始时间', { dateType: 'datetime' }),
      f('endTime', 'end_time', 'Date', 'datetime', '停止时间', { dateType: 'datetime', list: false }),
      f('orderStatus', 'order_status', 'String', 'char(1)', '状态', { dict: 'his_order_status', def: '0', query: 'eq' }),
      f('execBy', 'exec_by', 'String', 'varchar(64)', '执行护士', { list: false }),
      f('execTime', 'exec_time', 'Date', 'datetime', '执行时间', { dateType: 'datetime', list: false }),
    ],
    joins: [
      { alias: 'p', table: 'his_patient', on: 'p.patient_id = t.patient_id' },
      { alias: 'a', table: 'his_admission', on: 'a.adm_id = t.adm_id' },
      { alias: 'doc', table: 'his_doctor', on: 'doc.doctor_id = t.doctor_id' },
      { alias: 'dg', table: 'his_drug', on: 'dg.drug_id = t.drug_id' },
    ],
    orderBy: 't.order_id desc',
    hasExtraCode: 'order',
  },
  {
    table: 'his_nursing', entity: 'Nursing', cn: '护理记录', path: 'nursing', group: 'inpatient', pk: 'recordId', pkCol: 'record_id', complex: true,
    fields: [
      f('recordId', 'record_id', 'Long', 'bigint(20)', '记录ID', { pk: true }),
      f('admId', 'adm_id', 'Long', 'bigint(20)', '住院ID', { query: 'eq' }),
      f('patientId', 'patient_id', 'Long', 'bigint(20)', '患者'),
      f('patientName', '', 'String', '', '患者姓名', { persist: false, form: false, joinCol: 'p.patient_name' }),
      f('nurseName', 'nurse_name', 'String', 'varchar(50)', '护士'),
      f('recordTime', 'record_time', 'Date', 'datetime', '记录时间', { dateType: 'datetime' }),
      f('temperature', 'temperature', 'BigDecimal', 'decimal(4,1)', '体温(℃)'),
      f('pulse', 'pulse', 'Integer', 'int(4)', '脉搏(次/分)'),
      f('breath', 'breath', 'Integer', 'int(4)', '呼吸(次/分)'),
      f('bpHigh', 'bp_high', 'Integer', 'int(4)', '收缩压(mmHg)'),
      f('bpLow', 'bp_low', 'Integer', 'int(4)', '舒张压(mmHg)'),
      f('spo2', 'spo2', 'Integer', 'int(4)', '血氧(%)'),
      f('content', 'content', 'String', 'varchar(500)', '护理内容', { textarea: true, list: false }),
    ],
    joins: [{ alias: 'p', table: 'his_patient', on: 'p.patient_id = t.patient_id' }],
    orderBy: 't.record_time desc',
    extraApi: `// 查询住院的生命体征曲线数据\nexport function listNursingByAdm(admId) {\n  return request({ url: '/his/nursing/byAdm/' + admId, method: 'get' })\n}`,
    extraController: `    /** 按住院查询护理记录(体温单曲线用，时间正序) */\n    @GetMapping("/byAdm/{admId}")\n    public AjaxResult byAdm(@PathVariable("admId") Long admId)\n    {\n        Nursing q = new Nursing();\n        q.setAdmId(admId);\n        List<Nursing> list = nursingService.selectNursingList(q);\n        list.sort(java.util.Comparator.comparing(Nursing::getRecordTime, java.util.Comparator.nullsLast(java.util.Comparator.naturalOrder())));\n        return success(list);\n    }`,
  },
  // ================= 医技 =================
  {
    table: 'his_lab_test', entity: 'LabTest', cn: '检验单', path: 'lab', group: 'medtech', pk: 'testId', pkCol: 'test_id', complex: true, master: 'LabResult',
    fields: [
      f('testId', 'test_id', 'Long', 'bigint(20)', '检验ID', { pk: true }),
      f('testNo', 'test_no', 'String', 'varchar(30)', '检验单号', { query: 'eq' }),
      f('patientId', 'patient_id', 'Long', 'bigint(20)', '患者', { query: 'eq' }),
      f('patientName', '', 'String', '', '患者姓名', { persist: false, form: false, joinCol: 'p.patient_name' }),
      f('gender', '', 'String', '', '性别', { persist: false, form: false, joinCol: 'p.gender', dict: 'sys_user_sex' }),
      f('age', '', 'Integer', '', '年龄', { persist: false, form: false, joinCol: 'p.age' }),
      f('visitId', 'visit_id', 'Long', 'bigint(20)', '门诊就诊ID'),
      f('admId', 'adm_id', 'Long', 'bigint(20)', '住院ID'),
      f('doctorId', 'doctor_id', 'Long', 'bigint(20)', '申请医生'),
      f('doctorName', '', 'String', '', '申请医生', { persist: false, form: false, joinCol: 'doc.doctor_name' }),
      f('testItem', 'test_item', 'String', 'varchar(200)', '检验项目', { required: true, query: 'like' }),
      f('sampleType', 'sample_type', 'String', 'char(1)', '标本类型', { dict: 'his_sample_type', def: '0' }),
      f('status', 'status', 'String', 'char(1)', '状态', { dict: 'his_lab_status', def: '0', query: 'eq' }),
      f('applyTime', 'apply_time', 'Date', 'datetime', '申请时间', { dateType: 'datetime' }),
      f('sampleTime', 'sample_time', 'Date', 'datetime', '采样时间', { dateType: 'datetime', list: false }),
      f('reportTime', 'report_time', 'Date', 'datetime', '报告时间', { dateType: 'datetime' }),
      f('resultSummary', 'result_summary', 'String', 'varchar(1000)', '检验结论', { textarea: true, list: false }),
      f('reportBy', 'report_by', 'String', 'varchar(64)', '报告人', { list: false }),
    ],
    joins: [
      { alias: 'p', table: 'his_patient', on: 'p.patient_id = t.patient_id' },
      { alias: 'doc', table: 'his_doctor', on: 'doc.doctor_id = t.doctor_id' },
    ],
    orderBy: 't.test_id desc',
    hasExtraCode: 'lab',
  },
  {
    table: 'his_lab_result', entity: 'LabResult', cn: '检验结果', path: 'labResult', group: 'medtech', pk: 'resultId', pkCol: 'result_id', noPage: true, noController: true,
    fields: [
      f('resultId', 'result_id', 'Long', 'bigint(20)', '结果ID', { pk: true }),
      f('testId', 'test_id', 'Long', 'bigint(20)', '检验ID', { query: 'eq' }),
      f('itemName', 'item_name', 'String', 'varchar(100)', '项目名称'),
      f('resultValue', 'result_value', 'String', 'varchar(50)', '结果值'),
      f('unit', 'unit', 'String', 'varchar(20)', '单位'),
      f('refRange', 'ref_range', 'String', 'varchar(50)', '参考范围'),
      f('flag', 'flag', 'String', 'char(1)', '结果标识', { dict: 'his_lab_flag' }),
    ],
    orderBy: 't.result_id',
  },
  {
    table: 'his_exam', entity: 'Exam', cn: '检查单', path: 'exam', group: 'medtech', pk: 'examId', pkCol: 'exam_id', complex: true,
    fields: [
      f('examId', 'exam_id', 'Long', 'bigint(20)', '检查ID', { pk: true }),
      f('examNo', 'exam_no', 'String', 'varchar(30)', '检查单号', { query: 'eq' }),
      f('patientId', 'patient_id', 'Long', 'bigint(20)', '患者', { query: 'eq' }),
      f('patientName', '', 'String', '', '患者姓名', { persist: false, form: false, joinCol: 'p.patient_name' }),
      f('doctorId', 'doctor_id', 'Long', 'bigint(20)', '申请医生'),
      f('doctorName', '', 'String', '', '申请医生', { persist: false, form: false, joinCol: 'doc.doctor_name' }),
      f('examType', 'exam_type', 'String', 'char(1)', '检查类型', { dict: 'his_exam_type', required: true, def: '0' }),
      f('bodyPart', 'body_part', 'String', 'varchar(100)', '检查部位', { required: true }),
      f('purpose', 'purpose', 'String', 'varchar(500)', '检查目的', { textarea: true, list: false }),
      f('status', 'status', 'String', 'char(1)', '状态', { dict: 'his_exam_status', def: '0', query: 'eq' }),
      f('applyTime', 'apply_time', 'Date', 'datetime', '申请时间', { dateType: 'datetime' }),
      f('reportTime', 'report_time', 'Date', 'datetime', '报告时间', { dateType: 'datetime', list: false }),
      f('finding', 'finding', 'String', 'varchar(1000)', '影像所见', { textarea: true, list: false }),
      f('conclusion', 'conclusion', 'String', 'varchar(500)', '诊断结论', { textarea: true, list: false }),
      f('reportBy', 'report_by', 'String', 'varchar(64)', '报告人', { list: false }),
    ],
    joins: [
      { alias: 'p', table: 'his_patient', on: 'p.patient_id = t.patient_id' },
      { alias: 'doc', table: 'his_doctor', on: 'doc.doctor_id = t.doctor_id' },
    ],
    orderBy: 't.exam_id desc',
    hasExtraCode: 'exam',
  },
  {
    table: 'his_surgery', entity: 'Surgery', cn: '手术安排', path: 'surgery', group: 'medtech', pk: 'surgeryId', pkCol: 'surgery_id', complex: true,
    fields: [
      f('surgeryId', 'surgery_id', 'Long', 'bigint(20)', '手术ID', { pk: true }),
      f('surgeryNo', 'surgery_no', 'String', 'varchar(30)', '手术编号', { query: 'eq' }),
      f('surgeryName', 'surgery_name', 'String', 'varchar(100)', '手术名称', { required: true, query: 'like' }),
      f('patientId', 'patient_id', 'Long', 'bigint(20)', '患者', { required: true, query: 'eq', fk: { api: 'listPatient', module: 'patient', label: 'patientName', value: 'patientId' } }),
      f('patientName', '', 'String', '', '患者姓名', { persist: false, form: false, joinCol: 'p.patient_name' }),
      f('deptId', 'dept_id', 'Long', 'bigint(20)', '科室', { fk: { api: 'listDepartment', module: 'dept', label: 'deptName', value: 'deptId' } }),
      f('deptName', '', 'String', '', '科室', { persist: false, form: false, joinCol: 'd.dept_name' }),
      f('surgeonId', 'surgeon_id', 'Long', 'bigint(20)', '主刀医生', { fk: { api: 'listDoctor', module: 'doctor', label: 'doctorName', value: 'doctorId' } }),
      f('surgeonName', '', 'String', '', '主刀医生', { persist: false, form: false, joinCol: 'doc.doctor_name' }),
      f('anesthesia', 'anesthesia', 'String', 'char(1)', '麻醉方式', { dict: 'his_anesthesia', def: '0' }),
      f('roomNo', 'room_no', 'String', 'varchar(20)', '手术间'),
      f('level', 'level', 'String', 'char(1)', '手术级别', { dict: 'his_surgery_level', def: '0' }),
      f('planTime', 'plan_time', 'Date', 'datetime', '计划时间', { dateType: 'datetime' }),
      f('startTime', 'start_time', 'Date', 'datetime', '开始时间', { dateType: 'datetime', list: false }),
      f('endTime', 'end_time', 'Date', 'datetime', '结束时间', { dateType: 'datetime', list: false }),
      f('status', 'status', 'String', 'char(1)', '状态', { dict: 'his_surgery_status', def: '0', query: 'eq' }),
    ],
    joins: [
      { alias: 'p', table: 'his_patient', on: 'p.patient_id = t.patient_id' },
      { alias: 'd', table: 'his_department', on: 'd.dept_id = t.dept_id' },
      { alias: 'doc', table: 'his_doctor', on: 'doc.doctor_id = t.surgeon_id' },
    ],
    orderBy: 't.plan_time desc',
    extraApi: `// 手术状态流转(1开始 2完成 3取消)\nexport function changeSurgeryStatus(id, status) {\n  return request({ url: '/his/surgery/status/' + id + '/' + status, method: 'put' })\n}`,
    extraController: `    /** 手术状态流转 */\n    @PreAuthorize("@ss.hasPermi('his:surgery:edit')")\n    @Log(title = "手术安排", businessType = BusinessType.UPDATE)\n    @PutMapping("/status/{surgeryId}/{status}")\n    public AjaxResult changeStatus(@PathVariable("surgeryId") Long surgeryId, @PathVariable("status") String status)\n    {\n        Surgery s = new Surgery();\n        s.setSurgeryId(surgeryId);\n        s.setStatus(status);\n        if ("1".equals(status)) { s.setStartTime(new java.util.Date()); }\n        if ("2".equals(status)) { s.setEndTime(new java.util.Date()); }\n        return toAjax(surgeryService.updateSurgery(s));\n    }`,
  },
  // ================= 药库 =================
  {
    table: 'his_purchase', entity: 'Purchase', cn: '采购单', path: 'purchase', group: 'pharmacy', pk: 'purchaseId', pkCol: 'purchase_id', complex: true, master: 'PurchaseItem',
    fields: [
      f('purchaseId', 'purchase_id', 'Long', 'bigint(20)', '采购ID', { pk: true }),
      f('purchaseNo', 'purchase_no', 'String', 'varchar(30)', '采购单号', { query: 'eq' }),
      f('supplierId', 'supplier_id', 'Long', 'bigint(20)', '供应商', { required: true, query: 'eq', fk: { api: 'listSupplier', module: 'supplier', label: 'supplierName', value: 'supplierId' } }),
      f('supplierName', '', 'String', '', '供应商', { persist: false, form: false, joinCol: 's.supplier_name' }),
      f('totalAmount', 'total_amount', 'BigDecimal', 'decimal(12,2)', '合计金额(元)'),
      f('status', 'status', 'String', 'char(1)', '状态', { dict: 'his_purchase_status', def: '0', query: 'eq' }),
      f('inTime', 'in_time', 'Date', 'datetime', '入库时间', { dateType: 'datetime', list: false }),
    ],
    joins: [{ alias: 's', table: 'his_supplier', on: 's.supplier_id = t.supplier_id' }],
    orderBy: 't.purchase_id desc',
    hasExtraCode: 'purchase',
  },
  {
    table: 'his_purchase_item', entity: 'PurchaseItem', cn: '采购明细', path: 'purchaseItem', group: 'pharmacy', pk: 'itemId', pkCol: 'item_id', noPage: true, noController: true,
    fields: [
      f('itemId', 'item_id', 'Long', 'bigint(20)', '明细ID', { pk: true }),
      f('purchaseId', 'purchase_id', 'Long', 'bigint(20)', '采购ID', { query: 'eq' }),
      f('drugId', 'drug_id', 'Long', 'bigint(20)', '药品'),
      f('drugName', '', 'String', '', '药品名称', { persist: false, form: false, joinCol: 'dg.drug_name' }),
      f('specification', '', 'String', '', '规格', { persist: false, form: false, joinCol: 'dg.specification' }),
      f('quantity', 'quantity', 'Integer', 'int(11)', '数量'),
      f('price', 'price', 'BigDecimal', 'decimal(10,2)', '采购单价(元)'),
      f('amount', 'amount', 'BigDecimal', 'decimal(10,2)', '金额(元)'),
    ],
    joins: [{ alias: 'dg', table: 'his_drug', on: 'dg.drug_id = t.drug_id' }],
    orderBy: 't.item_id',
  },
  {
    table: 'his_stock_record', entity: 'StockRecord', cn: '出入库记录', path: 'stockrecord', group: 'pharmacy', pk: 'recordId', pkCol: 'record_id', createTimeQuery: true,
    fields: [
      f('recordId', 'record_id', 'Long', 'bigint(20)', '记录ID', { pk: true }),
      f('recordNo', 'record_no', 'String', 'varchar(30)', '单据号', { query: 'eq' }),
      f('recordType', 'record_type', 'String', 'char(1)', '变动类型', { dict: 'his_stock_type', query: 'eq' }),
      f('drugId', 'drug_id', 'Long', 'bigint(20)', '药品', { query: 'eq', fk: { api: 'listDrug', module: 'drug', label: 'drugName', value: 'drugId' } }),
      f('drugName', '', 'String', '', '药品名称', { persist: false, form: false, joinCol: 'dg.drug_name' }),
      f('specification', '', 'String', '', '规格', { persist: false, form: false, joinCol: 'dg.specification' }),
      f('quantity', 'quantity', 'Integer', 'int(11)', '变动数量'),
      f('beforeStock', 'before_stock', 'Integer', 'int(11)', '变动前库存'),
      f('afterStock', 'after_stock', 'Integer', 'int(11)', '变动后库存'),
      f('sourceId', 'source_id', 'Long', 'bigint(20)', '来源单据ID', { list: false }),
      f('operator', 'operator', 'String', 'varchar(64)', '经办人'),
    ],
    joins: [{ alias: 'dg', table: 'his_drug', on: 'dg.drug_id = t.drug_id' }],
    orderBy: 't.record_id desc',
  },
];

/** ======================== 菜单定义 ======================== */
// type: M目录 C菜单 F按钮; btns: 默认五按钮或自定义 [{n:'结算',p:'settle'}]
const MENUS = [
  { id: 3000, name: '智慧医疗', type: 'M', parent: 0, path: 'his', icon: 'guide', order: 2 },
  { id: 3001, name: '医疗工作台', type: 'C', parent: 3000, path: 'dashboard', comp: 'his/dashboard/index', perms: 'his:dashboard:list', icon: 'dashboard', order: 0 },
  { id: 3010, name: '基础数据', type: 'M', parent: 3000, path: 'base', icon: 'system', order: 1 },
  { id: 3011, name: '科室管理', type: 'C', parent: 3010, path: 'dept', comp: 'his/base/dept/index', perms: 'his:dept:list', icon: 'tree', order: 1, btns: 1 },
  { id: 3012, name: '医生管理', type: 'C', parent: 3010, path: 'doctor', comp: 'his/base/doctor/index', perms: 'his:doctor:list', icon: 'peoples', order: 2, btns: 1 },
  { id: 3013, name: '患者档案', type: 'C', parent: 3010, path: 'patient', comp: 'his/base/patient/index', perms: 'his:patient:list', icon: 'user', order: 3, btns: 1 },
  { id: 3014, name: '药品信息', type: 'C', parent: 3010, path: 'drug', comp: 'his/base/drug/index', perms: 'his:drug:list', icon: 'shopping', order: 4, btns: 1 },
  { id: 3015, name: '供应商管理', type: 'C', parent: 3010, path: 'supplier', comp: 'his/base/supplier/index', perms: 'his:supplier:list', icon: 'link', order: 5, btns: 1 },
  { id: 3016, name: '收费项目', type: 'C', parent: 3010, path: 'feeitem', comp: 'his/base/feeitem/index', perms: 'his:feeitem:list', icon: 'money', order: 6, btns: 1 },
  { id: 3017, name: '病区管理', type: 'C', parent: 3010, path: 'ward', comp: 'his/base/ward/index', perms: 'his:ward:list', icon: 'build', order: 7, btns: 1 },
  { id: 3018, name: '床位管理', type: 'C', parent: 3010, path: 'bed', comp: 'his/base/bed/index', perms: 'his:bed:list', icon: 'grid', order: 8, btns: 1 },
  { id: 3020, name: '门诊管理', type: 'M', parent: 3000, path: 'outpatient', icon: 'peoples', order: 2 },
  { id: 3021, name: '医生排班', type: 'C', parent: 3020, path: 'schedule', comp: 'his/outpatient/schedule/index', perms: 'his:schedule:list', icon: 'date', order: 1, btns: 1 },
  { id: 3022, name: '挂号管理', type: 'C', parent: 3020, path: 'registration', comp: 'his/outpatient/registration/index', perms: 'his:registration:list', icon: 'form', order: 2, btns: [{ n: '挂号查询', p: 'query' }, { n: '新增挂号', p: 'add' }, { n: '退号', p: 'refund' }, { n: '导出', p: 'export' }] },
  { id: 3023, name: '候诊队列', type: 'C', parent: 3020, path: 'queue', comp: 'his/outpatient/queue/index', perms: 'his:queue:list', icon: 'list', order: 3, btns: [{ n: '查询', p: 'query' }, { n: '叫号', p: 'call' }] },
  { id: 3024, name: '医生工作站', type: 'C', parent: 3020, path: 'workstation', comp: 'his/outpatient/workstation/index', perms: 'his:workstation:list', icon: 'edit', order: 4, btns: [{ n: '接诊', p: 'visit' }, { n: '开处方', p: 'rx' }] },
  { id: 3025, name: '电子病历', type: 'C', parent: 3020, path: 'emr', comp: 'his/outpatient/emr/index', perms: 'his:visit:list', icon: 'documentation', order: 5, btns: 1 },
  { id: 3026, name: '处方管理', type: 'C', parent: 3020, path: 'prescription', comp: 'his/outpatient/prescription/index', perms: 'his:prescription:list', icon: 'clipboard', order: 6, btns: [{ n: '处方查询', p: 'query' }, { n: '开具处方', p: 'add' }, { n: '作废', p: 'cancel' }, { n: '导出', p: 'export' }] },
  { id: 3027, name: '门诊收费', type: 'C', parent: 3020, path: 'charge', comp: 'his/outpatient/charge/index', perms: 'his:charge:list', icon: 'money', order: 7, btns: [{ n: '费用查询', p: 'query' }, { n: '收费结算', p: 'settle' }, { n: '退费', p: 'refund' }, { n: '导出', p: 'export' }] },
  { id: 3028, name: '药房发药', type: 'C', parent: 3020, path: 'dispense', comp: 'his/outpatient/dispense/index', perms: 'his:dispense:list', icon: 'shopping', order: 8, btns: [{ n: '查询', p: 'query' }, { n: '发药', p: 'dispense' }] },
  { id: 3030, name: '住院管理', type: 'M', parent: 3000, path: 'inpatient', icon: 'build', order: 3 },
  { id: 3031, name: '住院登记', type: 'C', parent: 3030, path: 'admission', comp: 'his/inpatient/admission/index', perms: 'his:admission:list', icon: 'form', order: 1, btns: 1 },
  { id: 3032, name: '医嘱管理', type: 'C', parent: 3030, path: 'order', comp: 'his/inpatient/order/index', perms: 'his:order:list', icon: 'list', order: 2, btns: [{ n: '医嘱查询', p: 'query' }, { n: '开立医嘱', p: 'add' }, { n: '执行', p: 'exec' }, { n: '停止', p: 'stop' }, { n: '导出', p: 'export' }] },
  { id: 3033, name: '护理记录', type: 'C', parent: 3030, path: 'nursing', comp: 'his/inpatient/nursing/index', perms: 'his:nursing:list', icon: 'star', order: 3, btns: 1 },
  { id: 3034, name: '出院结算', type: 'C', parent: 3030, path: 'discharge', comp: 'his/inpatient/discharge/index', perms: 'his:discharge:list', icon: 'money', order: 4, btns: [{ n: '查询', p: 'query' }, { n: '出院结算', p: 'settle' }] },
  { id: 3040, name: '医技管理', type: 'M', parent: 3000, path: 'medtech', icon: 'monitor', order: 4 },
  { id: 3041, name: '检验管理', type: 'C', parent: 3040, path: 'lab', comp: 'his/medtech/lab/index', perms: 'his:lab:list', icon: 'search', order: 1, btns: [{ n: '检验查询', p: 'query' }, { n: '新增申请', p: 'add' }, { n: '流程操作', p: 'flow' }, { n: '导出', p: 'export' }] },
  { id: 3042, name: '检查管理', type: 'C', parent: 3040, path: 'exam', comp: 'his/medtech/exam/index', perms: 'his:exam:list', icon: 'view', order: 2, btns: [{ n: '检查查询', p: 'query' }, { n: '新增申请', p: 'add' }, { n: '流程操作', p: 'flow' }, { n: '导出', p: 'export' }] },
  { id: 3043, name: '手术安排', type: 'C', parent: 3040, path: 'surgery', comp: 'his/medtech/surgery/index', perms: 'his:surgery:list', icon: 'time', order: 3, btns: 1 },
  { id: 3050, name: '药库管理', type: 'M', parent: 3000, path: 'pharmacy', icon: 'shopping', order: 5 },
  { id: 3051, name: '库存查询', type: 'C', parent: 3050, path: 'stock', comp: 'his/pharmacy/stock/index', perms: 'his:stock:list', icon: 'chart', order: 1, btns: [{ n: '查询', p: 'query' }, { n: '导出', p: 'export' }] },
  { id: 3052, name: '采购管理', type: 'C', parent: 3050, path: 'purchase', comp: 'his/pharmacy/purchase/index', perms: 'his:purchase:list', icon: 'shopping', order: 2, btns: [{ n: '采购查询', p: 'query' }, { n: '新建采购', p: 'add' }, { n: '入库审核', p: 'inbound' }, { n: '导出', p: 'export' }] },
  { id: 3053, name: '出入库记录', type: 'C', parent: 3050, path: 'stockrecord', comp: 'his/pharmacy/stockrecord/index', perms: 'his:stockrecord:list', icon: 'list', order: 3, btns: [{ n: '查询', p: 'query' }, { n: '导出', p: 'export' }] },
  { id: 3060, name: '统计报表', type: 'M', parent: 3000, path: 'report', icon: 'chart', order: 6 },
  { id: 3061, name: '经营统计', type: 'C', parent: 3060, path: 'statistics', comp: 'his/report/statistics/index', perms: 'his:statistics:list', icon: 'chart', order: 1, btns: [{ n: '查询', p: 'query' }] },
];

module.exports = { ENTITIES, DICTS, MENUS };

